# Generated by Django 5.0.14 on 2026-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('brasilapi_feriados', 'BrasilAPI - Feriados Nacionais'), ('open_brewery_db', 'Open Brewery DB')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('brasilapi_feriados', 'BrasilAPI - Feriados Nacionais'), ('open_brewery_db', 'Open Brewery DB')], max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('success', models.BooleanField()),
                ('records_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_item_per_source'),
        ),
    ]
